services:
  - type: web
    name: covid19-dashboard
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python scripts/generate_sample_data.py
    startCommand: streamlit run app/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
